### ISSUE TITLE
Use in nerd-dictation

### ISSUE THREAD

**Issue by nkeilar** [appvoid/vosper#1]
Good day, I apologize for my lack of understanding i would be interested to know if this could be a possible solution you use with

https://github.com/ideasman42/nerd-dictation/issues/74

Nerd-dictation  is a great tool for enabling you to use voice in any text box.  it's one downfall is that it doesn't have support for punctuation and correct grammar.  i'm actually using it now to write this post without using my keyboard much.  the incorporation of whisper with it's correct punctuation and grammar would be a great asset. 

i look forward to your feedback

**Comment by appvoid** [comment]
I think it is possible to create something similar with this tool. If you mean typing things on the keyboard with your voice, it's possible. I would recommend using another solution since this is meant for voice enabled apps on python. I may add that into a future update...

Anyway, xdotool seems to be pretty easy to use. I wouldn't recommend using vosk though.
